name: Setup Node
description: Composite action for setup-node
runs:
  using: 'composite'
  steps:
    - name: 🏗 Setup Node v16.18.0
      uses: actions/setup-node@v3
      with:
        node-version: 'v16.18.0'
        cache: 'yarn'

    - name: 🏗 Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
